name: xUnit.net PR Build (v2)
on:
  pull_request:
    branches:
    - v2
  workflow_dispatch:

jobs:
  build:
    name: "Build for PR"
    runs-on: windows-2022
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Clone source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            6.0.x

      - name: Get .NET information
        run: dotnet --info

      - name: "Build target: BuildAll"
        run: .\build.ps1 -target BuildAll

      - name: "Upload artifact: test-results"
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: artifacts/test
        if: always()
